/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oyun;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Admin
 */
public class GirisEkranı extends javax.swing.JFrame {
   
    public static final String RESIM_YOLU = "C:\\P2Oyun\\Resimler\\";
    public static final String TXT_YOLU = "C:\\P2Oyun\\TXTDosyalar\\";
    // 3 Hatalı giriş için sayaç ve sistemdeki şifreyi tutacağımız değişken
    int hataSayisi = 0;
    String kayitliSifre = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GirisEkranı.class.getName());

    /**
     * Creates new form GirisEkranı
     */
    public GirisEkranı() {
        initComponents();
        // Ekran açılır açılmaz şifre dosyasını kontrol et
        try {
            File sifreDosyasi = new File(TXT_YOLU + "sifre.txt");
            if (!sifreDosyasi.exists()) {
                sifreDosyasi.createNewFile();
            }
            
            Scanner okuyucu = new Scanner(sifreDosyasi);
            if (okuyucu.hasNextLine()) {
                // Şifre önceden belirlenmişse hafızaya al
                kayitliSifre = okuyucu.nextLine();
            } else {
                // Şifre dosyası boşsa, ilk şifreyi kullanıcıdan iste ve kaydet
                String yeniSifre = JOptionPane.showInputDialog(this, "İlk girişiniz. Lütfen bir şifre belirleyin:");
                if (yeniSifre != null && !yeniSifre.trim().isEmpty()) {
                    FileWriter yazici = new FileWriter(sifreDosyasi);
                    yazici.write(yeniSifre);
                    yazici.close();
                    kayitliSifre = yeniSifre;
                    JOptionPane.showMessageDialog(this, "Şifreniz başarıyla kaydedildi!");
                } else {
                    System.exit(0); // Şifre belirlemeden iptal ederse çık
                }
            }
            okuyucu.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Şifre dosyası okunurken hata oluştu: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        txtSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Şifre:");

        btnGiris.setText("Giriş Yap");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGiris)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnGiris)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
    String girilenSifre = new String(txtSifre.getPassword());
        String zaman = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));
        
        try {
            // Log dosyasına yazma işlemi (true parametresi ile üzerine ekleme yapar)
            FileWriter logYazici = new FileWriter(TXT_YOLU + "log.txt", true);
            
            if (girilenSifre.equals(kayitliSifre)) {
                // Şifre doğruysa
                logYazici.write("Başarılı giriş yapıldı - Tarih: " + zaman + "\n");
                logYazici.close();
                
                JOptionPane.showMessageDialog(this, "Giriş Başarılı!");
                // Adım 4'te Ana Oyun Ekranını buraya bağlayacağız.
                 this.dispose();
                 new OyunEkranı().setVisible(true);
                
            } else {
                // Şifre yanlışsa
                hataSayisi++;
                logYazici.write("Hatalı şifre denemesi - Tarih: " + zaman + "\n");
                logYazici.close();
                
                if (hataSayisi >= 3) {
                    JOptionPane.showMessageDialog(this, "3 kez hatalı giriş yaptınız. Program kapanıyor.");
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, "Hatalı şifre! Kalan hakkınız: " + (3 - hataSayisi));
                    txtSifre.setText(""); // Kutuyu temizle
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Log dosyasına yazılamadı: " + e.getMessage());
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GirisEkranı().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
